name: portfolio_app
description: Portfolio App - Aplikasi Mobile untuk menampilkan profil dan portofolio pengembang
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Jika Anda memiliki aset gambar, tambahkan di sini
  # assets:
  #   - assets/images/
  
  # Uncomment jika ingin menggunakan custom fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
